name = "bienestar"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2024-12-30"
compatibility_flags = [
  "nodejs_compat",
  "global_fetch_strictly_public"
]

# KV Namespace Bindings
[[kv_namespaces]]
binding = "SYMPTOMS_KV"
id = "cfe822214b194fc99021e294f460babc"

[[kv_namespaces]]
binding = "DISEASES_KV"
id = "08617170986e40c097e149eb8825ed0f"
