// AUTO-GENERATED - Do not edit manually
// Generated by generate-params.js

export const blogSlugs: string[] = [
  "biometria-hematica-importancia",
  "quimica-sanguinea-6-elementos",
  "examen-general-orina-interpretacion",
  "tipos-de-sangre-importancia",
  "perfil-lipidos-colesterol-hdl-ldl",
  "hipertension-asesino-silencioso",
  "alimentos-salud-cardiovascular",
  "electrocardiograma-basico",
  "papanicolaou-importancia",
  "perfil-hormonal-femenino-guia",
  "menopausia-mitos-realidades",
  "estudios-embarazo-trimestres",
  "check-up-infantil-guia",
  "parasitos-intestinales-copro",
  "alergias-vs-resfriado",
  "tamiz-neonatal-importancia",
  "tiroides-embarazo",
  "perfil-tiroideo-explicado",
  "hipotiroidismo-vs-hipertiroidismo",
  "nodulos-tiroideos",
  "resistencia-insulina-homa",
  "antigeno-prostatico-40-anos",
  "testosterona-baja-sintomas",
  "check-up-masculino-guia",
  "ets-hombres-deteccion",
  "hemoglobina-glucosilada-3-meses",
  "pie-diabetico-prevencion",
  "dano-renal-diabetes-microalbuminuria",
  "mitos-insulina",
  "vitamina-d-inmunidad",
  "vitamina-b12-cansancio",
  "hierro-ferritina-anemia",
  "electrolitos-hidratacion",
  "magnesio-beneficios",
  "cortisol-estres-impacto",
  "higado-graso-diagnostico",
  "acido-urico-gota",
  "importancia-ayuno-estudios",
  "marcadores-tumorales-explicados",
  "autoexploracion-mamaria-guia",
  "prevencion-cancer-cervicouterino",
  "marcador-ca125-ovario",
  "psa-cancer-prostata-info",
  "vivir-con-diabetes",
  "curva-tolerancia-glucosa",
  "diabetes-gestacional-riesgos",
  "indice-homa-explicado",
  "enfermedades-respiratorias-invierno",
  "influenza-vs-covid-diferencias",
  "cuidar-peso-fiestas",
  "regalo-salud-check-up",
  "propositos-salud-2023",
  "detox-post-fiestas-verdad",
  "perfil-hepatico-completo",
  "rinones-sanos-creatinina",
  "metabolismo-lento-obesidad",
  "sindrome-metabolico-criterios",
  "ets-guia-completa",
  "vih-deteccion-temprana",
  "vph-hombres-mujeres",
  "herpes-tipos-pruebas",
  "alergias-primaverales-ige",
  "pruebas-alergia-sangre-piel",
  "fortalecer-sistema-inmune",
  "grupo-rh-embarazo-incompatibilidad",
  "helicobacter-pylori-gastritis",
  "sangre-oculta-heces-colon",
  "intolerancia-lactosa-vs-alergia",
  "enfermedad-celiaca-gluten",
  "sop-diagnostico-laboratorio",
  "prolactina-alta-causas",
  "estradiol-progesterona-ciclo",
  "reserva-ovarica-antimulleriana",
  "menopausia-precoz-senales",
  "anticuerpos-tiroideos-hashimoto",
  "t3-reversa-metabolismo",
  "yodo-selenio-tiroides",
  "cancer-tiroides-tiroglobulina",
  "check-up-deportistas",
  "ck-daño-muscular",
  "anemia-deportista-ferritina",
  "lactato-resistencia-deportiva",
  "hormona-crecimiento-deporte",
  "check-up-geriatrico-60",
  "osteoporosis-prevencion",
  "b12-adultos-mayores-memoria",
  "artritis-reumatoide-diagnostico",
  "homocisteina-riesgo-cardiaco",
  "dimero-d-trombosis",
  "fibrinogeno-sangre",
  "lipoproteina-a-genetica",
  "tiempos-coagulacion-cirugia",
  "plaquetas-bajas-causas",
  "dengue-zika-diagnostico",
  "reticulocitos-medula-osea",
  "vsg-inflamacion-cuerpo",
  "andropausia-sintomas-tratamiento",
  "espermatobioscopia-fertilidad",
  "prolactina-hombres-disfuncion",
  "cultivo-uretral-infecciones",
  "chequeo-inmunologico-defensas",
  "zinc-beneficios-salud",
  "check-up-fin-ano-ideal",
  "alcohol-laboratorio-tiempo",
  "telemedicina-laboratorio-digital",
  "interpretar-resultados-pdf-linea",
  "covid-casera-vs-laboratorio",
  "curva-insulina-importancia",
  "sueroterapia-vitaminas-iv",
  "check-up-pareja-prenupcial",
  "infertilidad-estudios-pareja",
  "grupo-sanguineo-compatibilidad",
  "enfermedades-geneticas-recesivas",
  "dia-mundial-rinon-reglas",
  "cistatina-c-funcion-renal",
  "piedras-rinon-analisis-calculos",
  "orina-24-horas-recoleccion",
  "adolescentes-hormonas-acne",
  "anemia-ninos-aprendizaje",
  "obesidad-infantil-perfil-metabolico",
  "hormona-crecimiento-ninos-bajos",
  "panel-toxicologico-drogas",
  "bocio-nodulos-tiroides",
  "tiroiditis-posparto-explicada",
  "cancer-medular-tiroides-calcitonina",
  "suplementos-tiroides-guia",
  "microbiota-intestinal-segundo-cerebro",
  "calprotectina-heces-inflamacion",
  "amilasa-lipasa-pancreas",
  "coprologico-completo-digestion",
  "enzimas-cardiacas-infarto",
  "indice-aterogenico-riesgo",
  "estres-corazon-cortisol",
  "coenzima-q10-corazon",
  "bnp-falla-cardiaca",
  "fosfatasa-alcalina-significado",
  "calcio-fosforo-huesos",
  "marcadores-resorcion-osea-ctx",
  "sarcopenia-perdida-musculo-vejez",
  "anticuerpos-ana-lupus",
  "anti-dna-lupus-confirmacion",
  "sindrome-sjogren-anti-ro-la",
  "espondilitis-hla-b27",
  "celulas-le-historia",
  "marcador-ca153-cancer-mama",
  "brca1-brca2-genetica-cancer",
  "prolactina-secrecion-mamaria",
  "cultivo-vaginal-infecciones",
  "psa-libre-total-diferencia",
  "cultivo-semen-infecciones",
  "varicocele-fertilidad-masculina",
  "vasectomia-confirmacion-azoospermia",
  "check-up-ejecutivo-ideal",
  "fatiga-cronica-epstein-barr",
  "subir-plaquetas-naturalmente",
  "hierro-iv-vs-oral",
  "salud-preventiva-2025",
  "cortisol-ayuno-dopamina",
  "melatonina-insomnio-causas",
  "serotonina-depresion-analisis",
  "gaba-ansiedad-cerebro",
  "inflamacion-cronica-pcr",
  "omega-3-6-ratio-inflamacion",
  "antioxidantes-radicales-libres",
  "glutation-antioxidante-maestro",
  "dhea-s-hormona-juventud",
  "igf-1-crecimiento-insulina",
  "aldosterona-presion-arterial",
  "renina-volumen-sanguineo",
  "autismo-pruebas-geneticas",
  "tdah-marcadores-biologicos",
  "plomo-sangre-intoxicacion",
  "zinc-crecimiento-ninos",
  "check-up-mama-regalo",
  "fibromialgia-diagnostico-laboratorio",
  "fatiga-cronica-diagnostico",
  "b12-folato-energia",
  "complejo-b-guia-completa",
  "brucelosis-fiebre-malta",
  "salmonella-tifoidea-reacciones-febriles",
  "hepatitis-b-c-perfil",
  "hepatitis-a-comida",
  "torch-embarazo-riesgo",
  "proteinuria-espuma-orina",
  "electrolitos-orina-vs-sangre",
  "osmolaridad-urinaria-concentracion",
  "cristales-orina-tipos",
  "ggt-alcohol-higado",
  "fosfatasa-alcalina-elevada-causas",
  "bilirrubina-directa-indirecta",
  "alfa-fetoproteina-cancer-hepatico",
  "apolipoproteina-a-b-riesgo",
  "microalbuminuria-riesgo-cardiaco",
  "panel-cardiaco-avanzado",
  "muerte-subita-deportistas-prevencion",
  "exudado-faringeo-estreptococo",
  "cancer-ovario-sintomas",
  "endometriosis-laboratorio-ca125",
  "miomas-uterinos-anemia",
  "vph-genotipificacion-pcr",
  "cancer-testicular-marcadores",
  "disfuncion-erectil-causas",
  "hombres-viven-menos-prevencion",
  "prostata-agrandada-vs-cancer",
  "farmacogenomica-medicina-personalizada",
  "nutrigenetica-dieta-adn",
  "longevidad-biomarcadores",
  "futuro-laboratorio-clinico",
  "gracias-confianza-salud-2025",
  "enero-mes-salud-preventiva",
  "leer-resultados-2026",
  "nuevos-estudios-2026",
  "check-up-deportivo-pro-novedades",
  "porque-elegir-laboratorio-bienestar",
  "promociones-amor-amistad-2026",
  "laboratorio-clinico-tizayuca-precios",
  "cuanto-cuesta-analisis-sangre-tizayuca",
  "biometria-hematica-que-es-precio",
  "glucosa-en-ayunas-valores-normales",
  "check-up-basico-barato-que-incluye"
];

export const symptomSlugs: string[] = [
  {
    "slug": "dolor-abdominal-agudo"
  },
  {
    "slug": "dolor-abdominal-cronico"
  },
  {
    "slug": "ardor-al-orinar"
  },
  {
    "slug": "fatiga-cronica"
  },
  {
    "slug": "dolor-cabeza-intenso"
  },
  {
    "slug": "fiebre-alta-persistente"
  },
  {
    "slug": "tos-seca-persistente"
  },
  {
    "slug": "tos-con-flemas"
  },
  {
    "slug": "perdida-peso-inexplicable"
  },
  {
    "slug": "sed-excesiva"
  },
  {
    "slug": "dolor-pecho-angina"
  },
  {
    "slug": "caida-cabello-severa"
  },
  {
    "slug": "sangre-en-orina"
  },
  {
    "slug": "dolor-articular"
  },
  {
    "slug": "diarrea-cronica"
  },
  {
    "slug": "hinchazon-de-piernas"
  },
  {
    "slug": "vision-borrosa-repentina"
  },
  {
    "slug": "mareos-y-vertigo"
  },
  {
    "slug": "manchas-piel-nuevas"
  },
  {
    "slug": "retraso-menstrual-amenorrea"
  },
  {
    "slug": "dificultad-respirar-disnea"
  },
  {
    "slug": "zumbido-de-oidos"
  },
  {
    "slug": "acidez-reflujo"
  },
  {
    "slug": "estreñimiento-cronico"
  },
  {
    "slug": "sangrado-de-encias"
  },
  {
    "slug": "llanto-inconsolable-bebes"
  },
  {
    "slug": "manchas-rojas-que-no-desaparecen"
  },
  {
    "slug": "convulsiones-por-fiebre"
  },
  {
    "slug": "retraso-en-el-habla"
  },
  {
    "slug": "flujo-vaginal-con-olor"
  },
  {
    "slug": "picazon-vaginal"
  },
  {
    "slug": "ausencia-de-menstruacion"
  },
  {
    "slug": "dolor-fuerte-cabeza-embarazadas"
  },
  {
    "slug": "nauseas-matutinas-embarazo"
  },
  {
    "slug": "manchas-blancas-boca"
  },
  {
    "slug": "dificultad-para-tragar"
  },
  {
    "slug": "sangre-en-las-heces"
  },
  {
    "slug": "debilidad-muscular"
  },
  {
    "slug": "ronquidos-fuertes"
  },
  {
    "slug": "manchas-oscuras-melasma"
  },
  {
    "slug": "dolor-pelvico-femenino"
  },
  {
    "slug": "dolor-cuello-cervicalgia"
  },
  {
    "slug": "deformidad-articular"
  },
  {
    "slug": "ganglios-inflamados"
  },
  {
    "slug": "desmayos-repelinos-sincope"
  },
  {
    "slug": "ataques-de-panico"
  },
  {
    "slug": "insomnio-persistente"
  },
  {
    "slug": "falta-de-concentracion"
  },
  {
    "slug": "manchas-blancas-piel"
  },
  {
    "slug": "infecciones-respiratorias-recurrentes"
  }
];

export const diseaseSlugs: string[] = [
  {
    "slug": "hipoacusia-conductiva-y-neurosensorial"
  },
  {
    "slug": "otras-hipoacusias"
  },
  {
    "slug": "otalgia-y-secrecion-del-oido"
  },
  {
    "slug": "otosclerosis"
  },
  {
    "slug": "trastornos-de-la-funcion-vestibular"
  },
  {
    "slug": "sindromes-vertiginosos-en-enfermedades-clasificadas-en-otra-parte"
  },
  {
    "slug": "otros-trastornos-del-oido-interno"
  },
  {
    "slug": "otitis-media-no-supurativa"
  },
  {
    "slug": "otitis-media-supurativa-y-la-no-especificada"
  },
  {
    "slug": "otitis-media-en-enfermedades-clasificadas-en-otra-parte"
  },
  {
    "slug": "otitis-externa"
  },
  {
    "slug": "otros-trastornos-del-oido-externo"
  },
  {
    "slug": "trastornos-del-oido-externo-en-enfermedades-clasificadas-en-otra-parte"
  },
  {
    "slug": "trastornos-de-la-esclerotica"
  },
  {
    "slug": "queratitis"
  },
  {
    "slug": "opacidades-y-cicatrices-corneales"
  },
  {
    "slug": "otros-trastornos-de-la-cornea"
  },
  {
    "slug": "trastornos-de-la-esclerotica-y-de-la-cornea-en-enfermedades-clasificadas-en-otra"
  },
  {
    "slug": "iridociclitis"
  },
  {
    "slug": "otros-trastornos-del-iris-y-del-cuerpo-ciliar"
  },
  {
    "slug": "trastornos-del-iris-y-del-cuerpo-ciliar-en-enfermedades-clasificadas-en-otra-par"
  },
  {
    "slug": "conjuntivitis"
  },
  {
    "slug": "otros-trastornos-de-la-conjuntiva"
  },
  {
    "slug": "trastornos-de-la-conjuntiva-en-enfermedades-clasificadas-en-otra-parte"
  },
  {
    "slug": "orzuelo-y-calacio"
  },
  {
    "slug": "otras-inflamaciones-del-parpado"
  },
  {
    "slug": "otros-trastornos-de-los-parpados"
  },
  {
    "slug": "trastornos-del-parpado-en-enfermedades-clasificadas-en-otra-parte"
  },
  {
    "slug": "trastornos-del-aparato-lagrimal"
  },
  {
    "slug": "trastornos-de-la-orbita"
  },
  {
    "slug": "trastornos-del-aparato-lagrimal-y-de-la-orbita-en-enfermedades-clasificadas-en-o"
  },
  {
    "slug": "trastornos-fobicos-de-ansiedad"
  },
  {
    "slug": "otros-trastornos-de-ansiedad"
  },
  {
    "slug": "trastorno-obsesivo-compulsivo"
  },
  {
    "slug": "reaccion-al-estres-grave-y-trastornos-de-adaptacion"
  },
  {
    "slug": "trastornos-disociativos-de-conversion"
  },
  {
    "slug": "trastornos-somatomorfos"
  },
  {
    "slug": "otros-trastornos-neuroticos"
  },
  {
    "slug": "episodio-maniaco"
  },
  {
    "slug": "trastorno-afectivo-bipolar"
  },
  {
    "slug": "episodio-depresivo"
  },
  {
    "slug": "trastorno-depresivo-recurrente"
  },
  {
    "slug": "trastornos-del-humor-afectivos-persistentes"
  },
  {
    "slug": "otros-trastornos-del-humor-afectivos"
  },
  {
    "slug": "trastorno-del-humor-afectivo-no-especificado"
  },
  {
    "slug": "esquizofrenia"
  },
  {
    "slug": "trastorno-esquizotipico"
  },
  {
    "slug": "trastornos-delirantes-persistentes"
  },
  {
    "slug": "trastornos-psicoticos-agudos-y-transitorios"
  },
  {
    "slug": "trastorno-delirante-inducido"
  }
];

export const biomarkerSlugs: string[] = [
  "hemoglobina",
  "hematocrito",
  "eritrocitos-globulos-rojos",
  "vcm-volumen-corpuscular-medio",
  "hcm-hemoglobina-corpuscular-media",
  "cmhc-concentracion-media-de-hemoglobina",
  "rdw-ancho-de-distribucion-eritrocitaria",
  "reticulocitos",
  "leucocitos-globulos-blancos",
  "neutrofilos",
  "linfocitos",
  "monocitos",
  "eosinofilos",
  "basofilos",
  "bandas-neutrofilos-en-banda",
  "plaquetas-conteo-plaquetario",
  "vpm-volumen-plaquetario-medio",
  "tiempo-de-protrombina-tp",
  "ttpa-tiempo-de-tromboplastina-parcial",
  "inr-ratio-internacional-normalizado",
  "fibrinogeno",
  "dimero-d",
  "tiempo-de-sangrado",
  "glucosa-en-ayunas",
  "hemoglobina-glucosilada-hba1c",
  "insulina-basal",
  "indice-homa-ir-resistencia-a-insulina",
  "peptido-c",
  "curva-de-tolerancia-a-la-glucosa-2h",
  "creatinina-serica",
  "urea",
  "bun-nitrogeno-ureico",
  "acido-urico",
  "tasa-de-filtracion-glomerular-egfr",
  "cistatina-c",
  "depuracion-de-creatinina",
  "colesterol-total",
  "colesterol-ldl-malo",
  "colesterol-hdl-bueno",
  "colesterol-vldl",
  "trigliceridos",
  "indice-aterogenico",
  "lipoproteina-a-lp-a",
  "apolipoproteina-a1",
  "apolipoproteina-b",
  "bilirrubina-total",
  "bilirrubina-directa-conjugada",
  "bilirrubina-indirecta-no-conjugada",
  "tgo-ast-aspartato-aminotransferasa",
  "tgp-alt-alanina-aminotransferasa"
];
