vrrp_instance VI_1 {
    state BACKUP
    interface eth0          # Verifica tu interfaz
    virtual_router_id 51
    priority 90             # Prioridad menor para que sea Backup
    advert_int 1
    
    authentication {
        auth_type PASS
        auth_pass BienestarSecurePass!
    }
    
    virtual_ipaddress {
        192.168.1.200/24    # Misma IP Virtual que el Master
    }
    
    track_script {
        check_nginx
    }
}

vrrp_script check_nginx {
    script "/usr/bin/pgrep nginx"
    interval 2
    weight 2
}
