vrrp_instance VI_1 {
    state MASTER
    interface eth0          # Verifica tu interfaz con 'ip addr'
    virtual_router_id 51
    priority 100            # Prioridad alta para el Master
    advert_int 1
    
    authentication {
        auth_type PASS
        auth_pass BienestarSecurePass!
    }
    
    virtual_ipaddress {
        192.168.1.200/24    # IP Virtual Flotante (Ajustar a tu red)
    }
    
    # Script para verificar si Nginx está vivo
    track_script {
        check_nginx
    }
}

vrrp_script check_nginx {
    script "/usr/bin/pgrep nginx"
    interval 2
    weight 2
}
